spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost/microservice-practise
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9001
  servlet:
    context-path: /emp