spring:
  application:
    name: department_service_oct25
  datasource:
    url: jdbc:mysql://localhost/microservice-practise
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /dept
  port: 9001